language: clojure
lein: 2.9.1
install:
- "LEIN_USE_BOOTCLASSPATH=no lein cache-version"
- "LEIN_USE_BOOTCLASSPATH=no lein monolith each :in gorillalabs/kibit deps"
script:
- "LEIN_USE_BOOTCLASSPATH=no lein monolith each :in gorillalabs/kibit test-all"
- "LEIN_USE_BOOTCLASSPATH=no lein cache-version"
- "LEIN_USE_BOOTCLASSPATH=no lein monolith each install"
jdk:
  - openjdk8
  - openjdk11
  - oraclejdk11
